/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qtesla.test;


import org.bouncycastle.jce.provider.BouncyCastleProvider;
import java.security.Security;


public class App {


    public String getGreeting() {

        return "Hello world.";
    }

    public static void qtesla () {
        String testMessage = "Hello world! äöüÄÖÜß€";

        try {
            Qtesla qtesla = Qtesla.getInstance();

            byte[] sig = qtesla.sign(testMessage.getBytes());
            assert sig != null;
            System.out.println("Signature contains " + sig.length + " bytes");

            boolean verifyOk = qtesla.verify(testMessage.getBytes(), sig);

            if (verifyOk) {
                System.out.println("Verify successful");
            } else {
                System.out.println("Verify failed");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    public static void main(String[] args) {
        Security.addProvider(new BouncyCastleProvider());

        System.out.println(new App().getGreeting());

        qtesla();
    }
}
