/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qtesla.test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() throws Exception {
        String testMessage = "Hello world! äöüÄÖÜß€";

        Qtesla classUnderTest = Qtesla.getInstance();
        byte[] sig = classUnderTest.sign(testMessage.getBytes());
        assertNotNull(sig, "signature should be not null");

        assertTrue(classUnderTest.verify(testMessage.getBytes(), sig));
    }
}
